sudo: required

group: deprecated-2017Q2

language: node_js

node_js: 6.9.5

services:
  - mongodb

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost

before_script:
  - npm install -g grunt-cli
  - sleep 10

script:
  - grunt coverage
