language: node_js

node_js: 10

jobs:
  include:

  - stage: install, check code style and coverage
    if: tag IS blank
    addons:
      hosts:
      - localhost
    before_script:
    - npm install -g grunt-cli
    script:
    - if [ "$TRAVIS_BRANCH" != "master" ]; then grunt test; fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then grunt coverage; fi
