sudo: required

group: deprecated-2017Q2

language: node_js

node_js: 6.9.5

services:
  - mongodb

env:
  - CXX=g++-4.8

branches:
  only:
    - staging
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  hosts:
    - localhost

before_install:
  - sudo apt-get update && sudo apt-get install python make g++

before_script:
  - npm install -g grunt-cli
  - sleep 10

script:
  - grunt coverage
